### ISSUE TITLE
Start with 'Lorem ipsum'

### ISSUE THREAD

**Issue by tmorell** [knicklabs/lorem-ipsum.js#21]
Is there a way to force the generator to return 'Lorem ipsun' as the two first words?

**Comment by jonschlinkert** [comment]
`'Lorem ipsum ' + generate()`

**Comment by knicklabs** [comment]
This shouldn't be part of the library and a great suggestion has been provided so I'm closing this issue. Thanks.

**Comment by knicklabs** [comment]
> If it's in html mode it will be printed before the p tag, so it might be an option

Do you mean it might not be an option? If so, I agree. In that case, since this feature is not available in the library, I'd recommend generating your own html instead. All HTML mode does is wrap every paragraph in a `<p>` tag.

If you wanted to create several paragraphs of lorem ipsum text as HTML with the first paragraph beginning with "Lorem ipsum" you could do something like this:

```
lorem({ units: 'paragraphs', count: 5 }).split('\n').map((str, i) => i === 0 ? `<p>Lorem ipsum ${str.charAt(0).toLowerCase()}${str.slice(1)}</p>` : `<p>${str}</p>`).join('\n')
```

**Comment by hh2k** [comment]
> 

I was suggesting it should be an option, but the solution you presented worked great, so I am fine with doing it that way.
