### ISSUE TITLE
Empty string is returned for paragraphs when count is set to 0

### ISSUE THREAD

**Issue by jjnilton** [knicklabs/lorem-ipsum.js#61]
**Describe the bug**

Both `loremIpsum({count: 0, units: "words"})` and `loremIpsum({count: 0, units: "sentences"})` generate words/sentences based on a random number, but `loremIpsum({count: 0, units: "paragraphs"})` returns an empty string. Is this working as intended?

**Expected behavior**
I think all should have the same behavior.

**Version**
2.0.3

**Comment by knicklabs** [comment]
The primary reason this package was created was for the CLI. That was my use case. And the CLI does not support `0` as a count since it wasn't a requirement. What you've run up against is definitely an unspecified result. I certainly agree with you. I would expect all units to have the same behaviour. An empty string is probably the least surprising result for `0` `words`, `sentences`, and `paragraphs`. 

It's not something I plan to fix right now because I don't have the time or interest. I do accept pull requests to this repository though (there are other contributors) and this should be a pretty simple fix if you or anyone else coming across this issue wants to contribute a fix.

Should this get resolved in the future, I would bump up the major version number of the package to not impact anyone using this package whom may expect the current behaviour.

Thanks for taking the time to report this issue. I'll leave it open in case you or anyone wants to contribute a fix. I may even choose to pick this up myself one day, though not anytime soon.

**Comment by knicklabs** [comment]
The enhancement here would be to support `0` as a valid value for units.

**Comment by knicklabs** [comment]
Since this isn't a change that I require and I don't want to create extra work for myself, I've decided to close this issue out. The behaviour will NOT be changed in an upcoming version. Thanks for the suggestion nonetheless.
