### ISSUE TITLE
Keeps re-rendering the component on tab swop or right click

### ISSUE THREAD

**Issue by blaizeliebs** [knicklabs/lorem-ipsum.js#66]
It would seem that the package seems to re-render the component on tab switch or right-click, so when trying to inspect the code to debug it keeps refreshing.

**To Reproduce**
1. Install the latest package on Create-React-App
2. have it used on a component that is using lodash map and renders inside the map
3. Start app Go to browser and right click and notice each paragraph refresh

**Expected behavior**
Honestly expected it to just load dummy text once-off for each iteration in the array. I even created an IpsumGen component and used memo on it and it still re-renders.

**Code**
`import { memo } from 'react';
import { LoremIpsum } from 'lorem-ipsum';

const lorem = new LoremIpsum({
  sentencesPerParagraph: {
    max: 4,
    min: 1,
  },
  wordsPerSentence: {
    max: 16,
    min: 4,
  },
});

const IpsumGen = () => (
  <>
    <b>Generate LoremIpsum if Description is NULL</b> - {lorem.generateParagraphs(1)}
  </>
);

export default memo(IpsumGen);`

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser chrome
 - Version 96.0.4664.110

**Additional context**
As mentioned, I am using CRA

**Comment by knicklabs** [comment]
Hi @blaizeliebs. This library would not cause a re-render when used in React. However, when your component does re-render if you call one of the generate functions in your render function (i.e. `lorem.generateParagraphs(1)`) the text will not be the same as the last time your component rendered because it is randomized. This is not a bug, but the intended behaviour.

I suspect what you want is for the output to be deterministic so that the same lorem ipsum text is used whenever the "description" is null. The simplest way to achieve that would be to set a text variable at the module scope, beneath where you set `lorem`.

Like:

```javascript
const lorem = new LoremIpsum({
  sentencesPerParagraph: {
    max: 4,
    min: 1,
  },
  wordsPerSentence: {
    max: 16,
    min: 4,
  },
});

const IpsumGen = () => (
  <>
    {text}
  </>
);
```

The lorem text will change, for example, between page loads but it will not change from one render to the next when your component re-renders.

If you want something more deterministic, the LoremIpsum constructor takes a `random` option so you can provide a PRNG that can be seeded.

Hope that helps. I'm going to mark this as closed since it's not an issue with the library but an issue with usage.
